### ISSUE TITLE
Problème de compilation

### ISSUE THREAD

**Issue by ledoyen** [Ashiuuu/maven_training#1]
Hello,

La compilation échoue car l'import (inutilisé d'ailleurs) `import org.junit.Assert;` dans le fichier **SampleTest.java** référence une classe qu n'existe pas dans les dépendances spécifiées dans le fichier **pom.xml**.

Pour des raisons historiques, il est possible que ton IDE sache où trouver cette classe (dans une vielle version de junit), mais le lancement des tests en ligne de commande (par ex avec : `mvn clean test`) dans _l'état où est la branche main sur GitHub_ ne fonctionnera pas en local.

Si tu as des modifications locales non _commitées_ ou non _pushées_, cela peut expliquer la différence de comportement.

**Comment by Ashiuuu** [comment]
Bonjour,

Je viens de faire un git pull puis ./mvnw clean test et effectivement il ne trouve plus non plus le package org.junit. Mais du coup quelle dépendance je devrais mettre à la place ? org.junit ou junit tout court n'ont pas l'air de passer, donc je vois pas trop ce que je pourrais mettre à la place.

Par contre, un détail que je ne comprends pas trop, c'est que j'ai suivi le TP en, exécutant les commandes mvn sans problème, par contre en réessayant ce soir pour vérifier mvn n'est plus reconnue... Et sudo apt install maven n'a pas aidé... Après c'est pas si important mais je trouve ça quand même bizarre, sachant que je n'ai pas touché à la config de wsl.

**Comment by ledoyen** [comment]
tu peux simplement supprimer la ligne d'import qui pose problème, elle n'est de toute façon pas utilisée par la suite

**Comment by Ashiuuu** [comment]
Ca marche, mais je pensais qu'il fallait utiliser junit pour les tests et faire le code coverage 100% ?

Ah oui j'ai du le faire pour la session en cours mais j'ai redémarrer la wsl entre temps, j'avais oublié, merci !
